server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voting
    username: postgres
    password: postgres
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl